services:
  # ✅ PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vitaly_portfolio
      POSTGRES_USER: vitaly
      POSTGRES_PASSWORD: vitaly123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vitaly -d vitaly_portfolio"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ✅ Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ✅ Django Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - SECRET_KEY=docker-secret-key-for-development
      - DATABASE_URL=postgresql://vitaly:vitaly123@db:5432/vitaly_portfolio
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - GMAIL_USER=vitalivo@gmail.com
      - GMAIL_APP_PASSWORD=avsx tsjl brds cmlf
      - TELEGRAM_BOT_TOKEN=8447589158:AAF23a8ZvDBkZYLdfOL4t2p6j8AEsW9_ZKA
      - TELEGRAM_CHAT_ID=769259836
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
      - backend_media:/app/media

  # ✅ Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_SITE_URL: http://localhost:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_static:
  backend_media:
