name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ✅ BACKEND TESTS
  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements/development.txt
          
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
          SECRET_KEY: test-secret-key
          DEBUG: True
        run: |
          cd backend
          python manage.py test

  # ✅ FRONTEND BUILD TEST
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build
        env:
          NEXT_PUBLIC_API_URL: https://vitalyportfolio-api.railway.app
          NEXT_PUBLIC_SITE_URL: https://vitalyportfolio.vercel.app
        run: |
          cd frontend
          npm run build

  # ✅ DEPLOY NOTIFICATION
  deploy-notification:
    needs: [backend-test, frontend-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deployment Success
        run: |
          echo "🚀 Deployment successful!"
          echo "Frontend: https://vitalyportfolio.vercel.app"
          echo "Backend: https://vitalyportfolio-api.railway.app"
